language: csharp

matrix:
  include:
    - dotnet: 2.2.100
      mono: none
    - dotnet: latest
      mono: none
    - mono: latest

script:
  - cd Solution
  - dotnet restore
  - find . -type f -name '*.Tests.csproj' -exec dotnet test "{}" \;
